### ISSUE TITLE
java 21 features using which JDK download?

### ISSUE THREAD

**Issue by maxandersen** [wesleyegberto/java-new-features#2]
I couldn't get the InstanceMainMethodLauncher.java to work with latest java 21 OpenJDK build.

Which build did you use for it?

**Comment by wesleyegberto** [comment]
Hi Max

By the time that I was reading the JEP, its implementation were not released yet in EA build.
But I think it will be in the next build as its [PR was merged days ago](https://github.com/openjdk/jdk/pull/13689).
I will build the [main branch from JDK](https://github.com/openjdk/jdk) to start to test it.
